### ISSUE TITLE
Übung 2 - Aufgabe 1: ggplot2 in Abgabe

### ISSUE THREAD

**Issue by sTetkov** [chrlen/fsuMustererkennung#1]
Sollten wir nicht eher Standard Funktionen für die Plots benutzen?

**Comment by chrlen** [comment]
Das war nur um die Funktionen mal auszuprobieren. Ich würde Schukat-Talamazzini nächstes Mal fragen, ob das in Ordnung ist, wenn wir die ein oder andere Bibliotheken verwenden. Die Bibliothek ggplot2 erzielt auf jeden Fall einfacher bessere Ergebnisse als die die Plot-Funktionen. Bis wir seine Zustimmung haben sollten wir aber die Plot-Funktionen nutzen.

**Comment by sTetkov** [comment]
Ich würde morgen dann auf die Standard Library das umstellen, so können wir sonntags eine letzte Review machen bevor es geschickt wird
