### ISSUE TITLE
Änderung an der quant-Funktion

### ISSUE THREAD

**Issue by chrlen** [chrlen/fsuMustererkennung#2]
Ich glaube in den Zeilen 36 und 37  muss nicht ein weiteres Mal der Funktor b auf den Ausdruck aufgerufen werden. Ich glaube die Zeilen sollten folgendermaßen lauten. 

min(x[quantrange])->minval
max(x[quantrange])->maxval

Die in x[quantrange] enthaltenen Werte sind bereits quantisiert.

[quant.R](https://github.com/chrlen/fsuMustererkennung/blob/sascha/u2/quant.R)

**Comment by sTetkov** [comment]
Richtig, war eine sache di von einer vorherigen Version übrig geblieben war.
